default_stages: [pre-push]
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
      - id: end-of-file-fixer
        exclude: '.bumpversion.cfg'
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: revert-changelog-rc
        name: revert-changelog-rc
        entry: python scripts/revert_changelog_rc.py
        language: python
        files: CHANGELOG.md
        stages: [pre-commit]
      - id: tox
        name: tox
        entry: tox -e py312
        language: system
        always_run: true
        pass_filenames: false
